### ISSUE TITLE
`plot_series` function adding dates that don't exist in dataset

### ISSUE THREAD

**Issue by MMenchero** [Nixtla/utilsforecast#124]
### What happened + What you expected to happen

The `plot_series` function is adding additional dates that don't exist in the dataset. See reproducible example below. 

### Versions / Dependencies

Version 0.2.5

### Reproducible example

```python
import pandas as pd 
from utilsforecast.plotting import plot_series

algeria_economy = pd.read_csv('https://nixtla-public.s3.amazonaws.com/fpp4-datasets/algeria_exports.csv', parse_dates=['ds'])
plot_series(algeria_economy)
```
The plot starts on 1950, but the earliest date in the dataset is 1960-12-31. 

<img width="1389" alt="Screenshot 2024-09-17 at 20 11 15" src="https://github.com/user-attachments/assets/5a047aa3-8e6e-4def-ae4b-5cb62c628182">

### Issue Severity

High: It blocks me from completing my task.

**Comment by AzulGarza** [comment]
@jmoralez wdyt?

**Comment by jmoralez** [comment]
Seems to be due to this https://github.com/Nixtla/utilsforecast/blob/6d06cb1285e3bf38234958c6529613012d72bb11/utilsforecast/plotting.py#L394-L399
which was added in #92. Removing that produces this plot
![image](https://github.com/user-attachments/assets/da065e41-1a12-4aec-a10c-2056aa5d7864)

Is that the expected? I guess that's there for cases when the dates have days and can be too wide

**Comment by jmoralez** [comment]
We could also go with the plots produced by pandas, which don't add any padding
![image](https://github.com/user-attachments/assets/3a582987-1642-474a-ace2-5f1d7ff84e14)

**Comment by MMenchero** [comment]
Thank you, I think the first image should be the expected result.
