### ISSUE TITLE
Overall Performance Metric

### ISSUE THREAD

**Issue by baniasbaabe** [Nixtla/utilsforecast#32]
I see that the metrics are usually performed for every `unique_id` but is there a possibility to output an overall metric for all `unique_ids`?

**Comment by jmoralez** [comment]
Hey @baniasbaabe, thanks for raising this. Do you mean aggregate by unique_id first and then overall or just overall from the start?

**Comment by baniasbaabe** [comment]
Yes, just overall from start, so it shouldn‘t perform a groupby. I guess it‘s not possible rn, or?

**Comment by jmoralez** [comment]
It's usually not a good idea because the series can have different scales, so big errors in series with small values wouldn't produce a high RMSE for example. Also longer series would weigh more doing that. It's probably better to average the values across all ids, that way at least each serie weighs the same.
